[2024-05-28T03:09:34.301+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_lookup_ingest.ti_load_raw_data scheduled__2024-05-26T08:00:00+00:00 [queued]>
[2024-05-28T03:09:34.313+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_lookup_ingest.ti_load_raw_data scheduled__2024-05-26T08:00:00+00:00 [queued]>
[2024-05-28T03:09:34.314+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-05-28T03:09:34.314+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2024-05-28T03:09:34.314+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-05-28T03:09:34.332+0000] {taskinstance.py:1304} INFO - Executing <Task(DockerOperator): ti_load_raw_data> on 2024-05-26 08:00:00+00:00
[2024-05-28T03:09:34.337+0000] {standard_task_runner.py:55} INFO - Started process 754 to run task
[2024-05-28T03:09:34.341+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'franko_lookup_ingest', 'ti_load_raw_data', 'scheduled__2024-05-26T08:00:00+00:00', '--job-id', '277', '--raw', '--subdir', 'DAGS_FOLDER/challenge_dag.py', '--cfg-path', '/tmp/tmp1pv_8j42']
[2024-05-28T03:09:34.341+0000] {standard_task_runner.py:83} INFO - Job 277: Subtask ti_load_raw_data
[2024-05-28T03:09:34.417+0000] {task_command.py:389} INFO - Running <TaskInstance: franko_lookup_ingest.ti_load_raw_data scheduled__2024-05-26T08:00:00+00:00 [running]> on host a64b6410e10e
[2024-05-28T03:09:34.502+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=franko_lookup_ingest
AIRFLOW_CTX_TASK_ID=ti_load_raw_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-26T08:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-26T08:00:00+00:00
[2024-05-28T03:09:34.522+0000] {docker.py:284} INFO - Starting docker container from image my_dbt
[2024-05-28T03:09:36.731+0000] {docker.py:354} INFO - [0m03:09:36  Running with dbt=1.5.11
[2024-05-28T03:09:36.848+0000] {docker.py:354} INFO - [0m03:09:36  Registered adapter: postgres=1.5.11
[2024-05-28T03:09:36.922+0000] {docker.py:354} INFO - [0m03:09:36  Found 6 models, 6 tests, 0 snapshots, 0 analyses, 422 macros, 0 operations, 1 seed file, 1 source, 0 exposures, 0 metrics, 0 groups
[2024-05-28T03:09:36.924+0000] {docker.py:354} INFO - [0m03:09:36
[2024-05-28T03:09:36.994+0000] {docker.py:354} INFO - [0m03:09:36  Concurrency: 4 threads (target='dev')
[2024-05-28T03:09:36.994+0000] {docker.py:354} INFO - [0m03:09:36
[2024-05-28T03:09:36.997+0000] {docker.py:354} INFO - [0m03:09:36  1 of 1 START seed file dev.time_series_covid19_confirmed_global ................ [RUN]
[2024-05-28T03:10:50.893+0000] {docker.py:354} INFO - [0m03:10:50  1 of 1 OK loaded seed file dev.time_series_covid19_confirmed_global ............ [[32mINSERT 289[0m in 73.89s]
[2024-05-28T03:10:50.922+0000] {docker.py:354} INFO - [0m03:10:50
[2024-05-28T03:10:50.922+0000] {docker.py:354} INFO - [0m03:10:50  Finished running 1 seed in 0 hours 1 minutes and 14.00 seconds (74.00s).
[2024-05-28T03:10:50.934+0000] {docker.py:354} INFO - [0m03:10:50
[2024-05-28T03:10:50.935+0000] {docker.py:354} INFO - [0m03:10:50  [32mCompleted successfully[0m
[2024-05-28T03:10:50.936+0000] {docker.py:354} INFO - [0m03:10:50
[2024-05-28T03:10:50.936+0000] {docker.py:354} INFO - [0m03:10:50  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-05-28T03:10:52.122+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=franko_lookup_ingest, task_id=ti_load_raw_data, execution_date=20240526T080000, start_date=20240528T030934, end_date=20240528T031052
[2024-05-28T03:10:52.145+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2024-05-28T03:10:52.178+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
