[2024-05-27T18:30:25.153+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_python.create_seeds manual__2024-05-25T02:02:40.608195+00:00 [queued]>
[2024-05-27T18:30:25.165+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_python.create_seeds manual__2024-05-25T02:02:40.608195+00:00 [queued]>
[2024-05-27T18:30:25.166+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-05-27T18:30:25.166+0000] {taskinstance.py:1284} INFO - Starting attempt 25 of 25
[2024-05-27T18:30:25.166+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-05-27T18:30:25.182+0000] {taskinstance.py:1304} INFO - Executing <Task(DockerOperator): create_seeds> on 2024-05-25 02:02:40.608195+00:00
[2024-05-27T18:30:25.187+0000] {standard_task_runner.py:55} INFO - Started process 1937 to run task
[2024-05-27T18:30:25.190+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'franko_python', 'create_seeds', 'manual__2024-05-25T02:02:40.608195+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/example_dag.py', '--cfg-path', '/tmp/tmpkks7jop0']
[2024-05-27T18:30:25.190+0000] {standard_task_runner.py:83} INFO - Job 53: Subtask create_seeds
[2024-05-27T18:30:25.237+0000] {task_command.py:389} INFO - Running <TaskInstance: franko_python.create_seeds manual__2024-05-25T02:02:40.608195+00:00 [running]> on host b637b51b94ee
[2024-05-27T18:30:25.294+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=franko_python
AIRFLOW_CTX_TASK_ID=create_seeds
AIRFLOW_CTX_EXECUTION_DATE=2024-05-25T02:02:40.608195+00:00
AIRFLOW_CTX_TRY_NUMBER=25
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-25T02:02:40.608195+00:00
[2024-05-27T18:30:25.311+0000] {docker.py:284} INFO - Starting docker container from image my_dbt
[2024-05-27T18:30:27.637+0000] {docker.py:354} INFO - [0m18:30:27  Running with dbt=1.5.11
[2024-05-27T18:30:27.838+0000] {docker.py:354} INFO - [0m18:30:27  Registered adapter: postgres=1.5.11
[2024-05-27T18:30:27.861+0000] {docker.py:354} INFO - [0m18:30:27  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2024-05-27T18:30:29.209+0000] {docker.py:354} INFO - [0m18:30:29  Found 2 models, 4 tests, 0 snapshots, 0 analyses, 310 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
[2024-05-27T18:30:29.213+0000] {docker.py:354} INFO - [0m18:30:29
[2024-05-27T18:30:29.358+0000] {docker.py:354} INFO - [0m18:30:29  Concurrency: 4 threads (target='dev')
[2024-05-27T18:30:29.359+0000] {docker.py:354} INFO - [0m18:30:29
[2024-05-27T18:30:29.364+0000] {docker.py:354} INFO - [0m18:30:29  1 of 2 START sql table model dev.my_first_dbt_model ............................ [RUN]
[2024-05-27T18:30:29.624+0000] {docker.py:354} INFO - [0m18:30:29  1 of 2 OK created sql table model dev.my_first_dbt_model ....................... [[32mSELECT 2[0m in 0.26s]
[2024-05-27T18:30:29.628+0000] {docker.py:354} INFO - [0m18:30:29  2 of 2 START sql view model dev.my_second_dbt_model ............................ [RUN]
[2024-05-27T18:30:29.807+0000] {docker.py:354} INFO - [0m18:30:29  2 of 2 OK created sql view model dev.my_second_dbt_model ....................... [[32mCREATE VIEW[0m in 0.18s]
[2024-05-27T18:30:29.893+0000] {docker.py:354} INFO - [0m18:30:29
[2024-05-27T18:30:29.894+0000] {docker.py:354} INFO - [0m18:30:29  Finished running 1 table model, 1 view model in 0 hours 0 minutes and 0.68 seconds (0.68s).
[2024-05-27T18:30:29.907+0000] {docker.py:354} INFO - [0m18:30:29
[2024-05-27T18:30:29.908+0000] {docker.py:354} INFO - [0m18:30:29  [32mCompleted successfully[0m
[2024-05-27T18:30:29.909+0000] {docker.py:354} INFO - [0m18:30:29
[2024-05-27T18:30:29.909+0000] {docker.py:354} INFO - [0m18:30:29  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
[2024-05-27T18:30:31.208+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=franko_python, task_id=create_seeds, execution_date=20240525T020240, start_date=20240527T183025, end_date=20240527T183031
[2024-05-27T18:30:31.264+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2024-05-27T18:30:31.299+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
