[2024-05-25T06:01:32.715+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_python.create_seeds manual__2024-05-25T02:02:40.608195+00:00 [queued]>
[2024-05-25T06:01:32.725+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_python.create_seeds manual__2024-05-25T02:02:40.608195+00:00 [queued]>
[2024-05-25T06:01:32.725+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-05-25T06:01:32.725+0000] {taskinstance.py:1284} INFO - Starting attempt 11 of 11
[2024-05-25T06:01:32.725+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-05-25T06:01:32.740+0000] {taskinstance.py:1304} INFO - Executing <Task(DockerOperator): create_seeds> on 2024-05-25 02:02:40.608195+00:00
[2024-05-25T06:01:32.746+0000] {standard_task_runner.py:55} INFO - Started process 915 to run task
[2024-05-25T06:01:32.749+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'franko_python', 'create_seeds', 'manual__2024-05-25T02:02:40.608195+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/example_dag.py', '--cfg-path', '/tmp/tmp854fc6eq']
[2024-05-25T06:01:32.749+0000] {standard_task_runner.py:83} INFO - Job 32: Subtask create_seeds
[2024-05-25T06:01:32.806+0000] {task_command.py:389} INFO - Running <TaskInstance: franko_python.create_seeds manual__2024-05-25T02:02:40.608195+00:00 [running]> on host b637b51b94ee
[2024-05-25T06:01:32.874+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=franko_python
AIRFLOW_CTX_TASK_ID=create_seeds
AIRFLOW_CTX_EXECUTION_DATE=2024-05-25T02:02:40.608195+00:00
AIRFLOW_CTX_TRY_NUMBER=11
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-25T02:02:40.608195+00:00
[2024-05-25T06:01:32.900+0000] {docker.py:284} INFO - Starting docker container from image my_dbt
[2024-05-25T06:01:35.961+0000] {docker.py:354} INFO - [0m06:01:35  Running with dbt=1.5.11
[2024-05-25T06:01:36.178+0000] {docker.py:354} INFO - [0m06:01:36  Registered adapter: postgres=1.5.11
[2024-05-25T06:01:36.202+0000] {docker.py:354} INFO - [0m06:01:36  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2024-05-25T06:01:37.304+0000] {docker.py:354} INFO - [0m06:01:37  Found 2 models, 4 tests, 0 snapshots, 0 analyses, 310 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
[2024-05-25T06:01:37.305+0000] {docker.py:354} INFO - [0m06:01:37
[2024-05-25T06:01:37.379+0000] {docker.py:354} INFO - [0m06:01:37  Concurrency: 4 threads (target='dev')
[2024-05-25T06:01:37.380+0000] {docker.py:354} INFO - [0m06:01:37
[2024-05-25T06:01:37.383+0000] {docker.py:354} INFO - [0m06:01:37  1 of 2 START sql table model dev.my_first_dbt_model ............................ [RUN]
[2024-05-25T06:01:37.517+0000] {docker.py:354} INFO - [0m06:01:37  1 of 2 OK created sql table model dev.my_first_dbt_model ....................... [[32mSELECT 2[0m in 0.13s]
[2024-05-25T06:01:37.520+0000] {docker.py:354} INFO - [0m06:01:37  2 of 2 START sql view model dev.my_second_dbt_model ............................ [RUN]
[2024-05-25T06:01:37.582+0000] {docker.py:354} INFO - [0m06:01:37  2 of 2 OK created sql view model dev.my_second_dbt_model ....................... [[32mCREATE VIEW[0m in 0.06s]
[2024-05-25T06:01:37.596+0000] {docker.py:354} INFO - [0m06:01:37
[2024-05-25T06:01:37.596+0000] {docker.py:354} INFO - [0m06:01:37  Finished running 1 table model, 1 view model in 0 hours 0 minutes and 0.29 seconds (0.29s).
[2024-05-25T06:01:37.605+0000] {docker.py:354} INFO - [0m06:01:37
[2024-05-25T06:01:37.605+0000] {docker.py:354} INFO - [0m06:01:37  [32mCompleted successfully[0m
[2024-05-25T06:01:37.606+0000] {docker.py:354} INFO - [0m06:01:37
[2024-05-25T06:01:37.606+0000] {docker.py:354} INFO - [0m06:01:37  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
[2024-05-25T06:01:38.708+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=franko_python, task_id=create_seeds, execution_date=20240525T020240, start_date=20240525T060132, end_date=20240525T060138
[2024-05-25T06:01:38.753+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2024-05-25T06:01:38.781+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
