[2024-05-28T02:55:04.979+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_lookup_ingest.ti_test_stage_data manual__2024-05-27T21:49:08.726117+00:00 [queued]>
[2024-05-28T02:55:05.005+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_lookup_ingest.ti_test_stage_data manual__2024-05-27T21:49:08.726117+00:00 [queued]>
[2024-05-28T02:55:05.005+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-05-28T02:55:05.005+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 4
[2024-05-28T02:55:05.006+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-05-28T02:55:05.055+0000] {taskinstance.py:1304} INFO - Executing <Task(DockerOperator): ti_test_stage_data> on 2024-05-27 21:49:08.726117+00:00
[2024-05-28T02:55:05.066+0000] {standard_task_runner.py:55} INFO - Started process 2217 to run task
[2024-05-28T02:55:05.072+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'franko_lookup_ingest', 'ti_test_stage_data', 'manual__2024-05-27T21:49:08.726117+00:00', '--job-id', '239', '--raw', '--subdir', 'DAGS_FOLDER/challenge_dag.py', '--cfg-path', '/tmp/tmplfbalxhy']
[2024-05-28T02:55:05.073+0000] {standard_task_runner.py:83} INFO - Job 239: Subtask ti_test_stage_data
[2024-05-28T02:55:05.226+0000] {task_command.py:389} INFO - Running <TaskInstance: franko_lookup_ingest.ti_test_stage_data manual__2024-05-27T21:49:08.726117+00:00 [running]> on host a64b6410e10e
[2024-05-28T02:55:05.407+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=franko_lookup_ingest
AIRFLOW_CTX_TASK_ID=ti_test_stage_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-27T21:49:08.726117+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-27T21:49:08.726117+00:00
[2024-05-28T02:55:05.464+0000] {docker.py:284} INFO - Starting docker container from image my_dbt
[2024-05-28T02:55:09.000+0000] {docker.py:354} INFO - [0m02:55:09  Running with dbt=1.5.11
[2024-05-28T02:55:09.155+0000] {docker.py:354} INFO - [0m02:55:09  Registered adapter: postgres=1.5.11
[2024-05-28T02:55:09.312+0000] {docker.py:354} INFO - [0m02:55:09  Found 6 models, 6 tests, 0 snapshots, 0 analyses, 422 macros, 0 operations, 1 seed file, 1 source, 0 exposures, 0 metrics, 0 groups
[2024-05-28T02:55:09.314+0000] {docker.py:354} INFO - [0m02:55:09
[2024-05-28T02:55:09.375+0000] {docker.py:354} INFO - [0m02:55:09  Concurrency: 4 threads (target='dev')
[2024-05-28T02:55:09.376+0000] {docker.py:354} INFO - [0m02:55:09
[2024-05-28T02:55:09.379+0000] {docker.py:354} INFO - [0m02:55:09  1 of 2 START test not_null_silver_unpivot_covid_geo_Country_Region ............. [RUN]
[2024-05-28T02:55:09.380+0000] {docker.py:354} INFO - [0m02:55:09  2 of 2 START test not_null_silver_unpivot_covid_geo_transf_province_state ...... [RUN]
[2024-05-28T02:55:14.839+0000] {docker.py:354} INFO - [0m02:55:14  2 of 2 PASS not_null_silver_unpivot_covid_geo_transf_province_state ............ [[32mPASS[0m in 5.46s]
[2024-05-28T02:55:15.944+0000] {docker.py:354} INFO - [0m02:55:15  1 of 2 PASS not_null_silver_unpivot_covid_geo_Country_Region ................... [[32mPASS[0m in 6.56s]
[2024-05-28T02:55:16.005+0000] {docker.py:354} INFO - [0m02:55:16
[2024-05-28T02:55:16.005+0000] {docker.py:354} INFO - [0m02:55:16  Finished running 2 tests in 0 hours 0 minutes and 6.69 seconds (6.69s).
[2024-05-28T02:55:16.025+0000] {docker.py:354} INFO - [0m02:55:16
[2024-05-28T02:55:16.025+0000] {docker.py:354} INFO - [0m02:55:16  [32mCompleted successfully[0m
[2024-05-28T02:55:16.026+0000] {docker.py:354} INFO - [0m02:55:16
[2024-05-28T02:55:16.026+0000] {docker.py:354} INFO - [0m02:55:16  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
[2024-05-28T02:55:17.349+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=franko_lookup_ingest, task_id=ti_test_stage_data, execution_date=20240527T214908, start_date=20240528T025504, end_date=20240528T025517
[2024-05-28T02:55:17.395+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2024-05-28T02:55:17.425+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
