[2024-05-28T03:03:14.060+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_lookup_ingest.ti_test_stage_data manual__2024-05-27T21:49:08.726117+00:00 [queued]>
[2024-05-28T03:03:14.068+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_lookup_ingest.ti_test_stage_data manual__2024-05-27T21:49:08.726117+00:00 [queued]>
[2024-05-28T03:03:14.068+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-05-28T03:03:14.068+0000] {taskinstance.py:1284} INFO - Starting attempt 5 of 5
[2024-05-28T03:03:14.068+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-05-28T03:03:14.084+0000] {taskinstance.py:1304} INFO - Executing <Task(DockerOperator): ti_test_stage_data> on 2024-05-27 21:49:08.726117+00:00
[2024-05-28T03:03:14.088+0000] {standard_task_runner.py:55} INFO - Started process 269 to run task
[2024-05-28T03:03:14.091+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'franko_lookup_ingest', 'ti_test_stage_data', 'manual__2024-05-27T21:49:08.726117+00:00', '--job-id', '274', '--raw', '--subdir', 'DAGS_FOLDER/challenge_dag.py', '--cfg-path', '/tmp/tmpyvt6wpsj']
[2024-05-28T03:03:14.091+0000] {standard_task_runner.py:83} INFO - Job 274: Subtask ti_test_stage_data
[2024-05-28T03:03:14.143+0000] {task_command.py:389} INFO - Running <TaskInstance: franko_lookup_ingest.ti_test_stage_data manual__2024-05-27T21:49:08.726117+00:00 [running]> on host a64b6410e10e
[2024-05-28T03:03:14.210+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=franko_lookup_ingest
AIRFLOW_CTX_TASK_ID=ti_test_stage_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-27T21:49:08.726117+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-27T21:49:08.726117+00:00
[2024-05-28T03:03:14.227+0000] {docker.py:284} INFO - Starting docker container from image my_dbt
[2024-05-28T03:03:16.648+0000] {docker.py:354} INFO - [0m03:03:16  Running with dbt=1.5.11
[2024-05-28T03:03:16.758+0000] {docker.py:354} INFO - [0m03:03:16  Registered adapter: postgres=1.5.11
[2024-05-28T03:03:16.830+0000] {docker.py:354} INFO - [0m03:03:16  Found 6 models, 6 tests, 0 snapshots, 0 analyses, 422 macros, 0 operations, 1 seed file, 1 source, 0 exposures, 0 metrics, 0 groups
[2024-05-28T03:03:16.832+0000] {docker.py:354} INFO - [0m03:03:16
[2024-05-28T03:03:16.887+0000] {docker.py:354} INFO - [0m03:03:16  Concurrency: 4 threads (target='dev')
[2024-05-28T03:03:16.887+0000] {docker.py:354} INFO - [0m03:03:16
[2024-05-28T03:03:16.891+0000] {docker.py:354} INFO - [0m03:03:16  1 of 2 START test not_null_silver_unpivot_covid_geo_Country_Region ............. [RUN]
[2024-05-28T03:03:16.891+0000] {docker.py:354} INFO - [0m03:03:16  2 of 2 START test not_null_silver_unpivot_covid_geo_transf_province_state ...... [RUN]
[2024-05-28T03:03:22.468+0000] {docker.py:354} INFO - [0m03:03:22  2 of 2 PASS not_null_silver_unpivot_covid_geo_transf_province_state ............ [[32mPASS[0m in 5.57s]
[2024-05-28T03:03:23.006+0000] {docker.py:354} INFO - [0m03:03:23  1 of 2 PASS not_null_silver_unpivot_covid_geo_Country_Region ................... [[32mPASS[0m in 6.11s]
[2024-05-28T03:03:23.120+0000] {docker.py:354} INFO - [0m03:03:23
[2024-05-28T03:03:23.120+0000] {docker.py:354} INFO - [0m03:03:23  Finished running 2 tests in 0 hours 0 minutes and 6.29 seconds (6.29s).
[2024-05-28T03:03:23.132+0000] {docker.py:354} INFO - [0m03:03:23
[2024-05-28T03:03:23.132+0000] {docker.py:354} INFO - [0m03:03:23  [32mCompleted successfully[0m
[2024-05-28T03:03:23.132+0000] {docker.py:354} INFO - [0m03:03:23
[2024-05-28T03:03:23.133+0000] {docker.py:354} INFO - [0m03:03:23  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
[2024-05-28T03:03:23.954+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=franko_lookup_ingest, task_id=ti_test_stage_data, execution_date=20240527T214908, start_date=20240528T030314, end_date=20240528T030323
[2024-05-28T03:03:24.008+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2024-05-28T03:03:24.027+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
